### ISSUE TITLE
Time data aggregation function for situation report

### ISSUE THREAD

**Issue by DavidSoSiZoch** [hzi-braunschweig/SORMAS-Stats-next-gen#115]
Function that aggregates the raw data exported from sormas by date (day/week/month/year)

**Comment by bernardsilenou** [comment]
@DavidSoSiZoch 
You can have a look at this comment https://github.com/hzi-braunschweig/SORMAS-Project/issues/3916#issuecomment-770090031 or epitools https://rdrr.io/cran/epitools/man/as.week.html

**Comment by DavidSoSiZoch** [comment]
Thank you

Am Do., 27. Jan. 2022 um 10:56 Uhr schrieb Silelou Bernard Chawo <
***@***.***>:
