### ISSUE TITLE
Access errors on last commits : package 'attempt' is missing

### ISSUE THREAD

**Issue by GRADeS-Gwen** [hzi-braunschweig/SORMAS-Stats-next-gen#132]
### Bug Description

Can not run Sormas-stats from lasts "development" commits. It say that package 'attempt' is missing.

### Steps to Reproduce

1. git pull lasts commit, build and deploy
2. try to access .../sormas-stats-shinyapp/

### Screenshots

```
sormas-stats_1  | [2022-04-06T15:23:53.287] [INFO] shiny-server - [/srv/shiny-server/sormas-stats-shinyapp:24] Error in library(attempt) : there is no package called 'attempt'
sormas-stats_1  | [2022-04-06T15:23:53.288] [INFO] shiny-server - [/srv/shiny-server/sormas-stats-shinyapp:24] Calls: runApp ... ..stacktraceon.. -> source -> withVisible -> eval -> eval -> library
sormas-stats_1  | [2022-04-06T15:23:53.293] [INFO] shiny-server - [/srv/shiny-server/sormas-stats-shinyapp:24] Execution halted
sormas-stats_1  | [2022-04-06T15:23:53.340] [INFO] shiny-server - [/srv/shiny-server/sormas-stats-shinyapp:24] 
sormas-stats_1  | [2022-04-06T15:23:53.345] [INFO] shiny-server - Error getting worker: Error: The application exited during initialization.
```

### System Details

* SORMAS version: 1.67.1

### Additional Information

Tried to rollback some commit, and it seem the commit "52ff53b43091dd9e086e02346a25af6c47f9f7e1" is responsible of the problem.

**Comment by bernardsilenou** [comment]
@carolinverset  @GRADeS-Gwen 
Sorry, it was my fault, I did not restore the list of packages in the renv.lock file.
Please pull the new changes and restore the packages ` renv::restore() ` before launching the app.
